language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
  - node_modules

script:
  - npm run build

after_success:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
